// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-security using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=localeResolver_26a3deacfe
ROOST_METHOD_SIG_HASH=localeResolver_48401fafe2

Scenario 1: Testing the Default Locale

Details:  
  TestName: testDefaultLocale
  Description: This test is to verify if the method sets the default Locale as English. 
Execution:
  Arrange: No setup is required as we are checking the default value.
  Act: Call the localeResolver method.
  Assert: Check if the returned LocaleResolver object's default locale is set to English.
Validation: 
  The assertion validates if the default Locale has been set to English. As per the function creation rules, it should be set to English by default which is significant for content localization across different geographical and cultural audiences.

Scenario 2: Testing the Returned Object Type

Details:  
  TestName: testReturnedObjectType
  Description: This test is to check that the method's return type is indeed an instance of LocaleResolver.
Execution:
  Arrange: No setup required as we're validating the returned object type only.
  Act: Call the localeResolver method.
  Assert: Validate if the returned object is an instance of LocaleResolver
Validation: 
  Asserting the type of returned object validates the method’s conforming to return an object of type LocaleResolver. This is vital to ensure that subsequent operations meant for a LocaleResolver instance can be performed without runtime errors.

Scenario 3: Testing Non-null Return Value 

Details:  
  TestName: testNonNullReturnValue
  Description: This test is to confirm that the localeResolver method never returns a null object.
Execution:
  Arrange: No setup required as we are validating the non-null nature of the returned object.
  Act: Call the localeResolver method.
  Assert: Assert that the returned object isn't null.
Validation: 
  The assertion is aimed at verifying that our method always returns a concrete instance of LocaleResolver. This is vital to avoid NullPointerException that can be caused by calling methods on null objects.
*/

// ********RoostGPT********
@Test
public void testReturnedObjectType(){
    LocaleResolver localeResolver = localeResolver();
    Assert.assertTrue("Returned object should be an instance of LocaleResolver", 
                     localeResolver instanceof LocaleResolver);
    Assert.assertTrue("Returned object should be an instance of CookieLocaleResolver", 
                     localeResolver instanceof CookieLocaleResolver);
}
